### ISSUE TITLE
Missing 1.26 binary

### ISSUE THREAD

**Issue by ghost** [claunia/edccchk#1]
Hey claunia, could compile/post binaries for 1.26? Thanks. :)

**Comment by claunia** [comment]
Sure, I'll try to get a minute today to do it.
But maybe you're better suited with [DiscImageChef](http://github.com/claunia/DiscImageChef)? Does the same but supports disc images.

**Comment by ghost** [comment]
Someone else asked about it, I just happen to have a github for other projects so I dumped the request in. I suppose they already have it setup in their tool chain, although not hard to change. Still, would like it just for my own tool collection.

**Comment by claunia** [comment]
@RoyBatty64 there they are.
